name: Compile JOSS Paper
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: 
          sudo apt-get update && sudo apt-get install -y pandoc texlive texlive-xetex

      - name: Compile PDF
        run: 
          pandoc paper/paper.md -o paper/paper.pdf --bibliography=paper/paper.bib --filter pandoc-citeproc
          pandoc paper/paper.md -o paper/paper_JOSS.md --lua-filter=.github/normalize-metadata.lua

      - name: Compile Final PDF
        run:
          pandoc paper/paper_JOSS.md -o paper/paper.pdf --pdf-engine=xelatex
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: joss-paper-pdf
          path: paper.pdf

